version: '2'
services:
  veto-app:
    image: schatzop/veto-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://veto-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=VeTo
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    volumes:
      - <PATH_TO_FOLDER>/data:/dataX/VeTo/VeTo-data
      - <PATH_TO_FOLDER>/results:/dataX/VeTo/VeTo-results
    ports:
      - 8282:8282

  veto-mongodb:
    extends:
      file: mongodb.yml
      service: spot-mongodb
